# Generated by Django 3.0 on 2019-12-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0002_auto_20191218_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='password',
            new_name='bits_id',
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
