# Generated by Django 3.0 on 2019-12-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0005_auto_20191219_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='time_stamp1',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
