# Generated by Django 3.0 on 2019-12-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0006_siteuser_time_stamp1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='siteuser',
            name='assigned_place',
            field=models.CharField(default='', max_length=100),
        ),
    ]
