# Generated by Django 3.0.1 on 2019-12-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0008_auto_20191220_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitesettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_number', models.IntegerField(default=0)),
                ('allow_change_participation', models.BooleanField(default=True)),
                ('matches_already_made', models.BooleanField(default=False)),
                ('data_populated', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='siteuser',
            old_name='participate_request_changeTime',
            new_name='participate_request_change_pr',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='match_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteuser',
            name='matched_with',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteuser',
            name='priority_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='year',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='bits_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
