# Generated by Django 3.0.1 on 2019-12-26 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0009_auto_20191226_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='matches_already_made',
            new_name='allow_user_match',
        ),
    ]
