# Generated by Django 3.0.1 on 2019-12-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0010_auto_20191226_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pr_no',
            field=models.IntegerField(default=0),
        ),
    ]
